use_frameworks!

target 'HealthStat' do

pod 'Macaw', '0.8.0'

end
post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '3.0.1'
		end
	end
end

